package my.Geovise;//Stating what package this file is part of. It is part of the my.contacteditor package

import java.awt.event.ActionEvent;// Importing the action event and listener, to check when the user clicks on an object in the frame
import java.awt.event.ActionListener;
import java.util.Calendar;//  Allows me to create the clock
import javax.swing.ImageIcon;// Importing to allow me to set the default icon when the frame is opened.
import javax.swing.JFrame;
import javax.swing.JOptionPane;//Allows for the use of option panes
import javax.swing.Timer; // Allows for the use of a timer class
import static my.Geovise.MainUI.OptionOpen;// Importing global variables :

public class CaseStudies extends javax.swing.JFrame {// Extends the JFrame allows for the gui functionality

    /**
     * Creates new form CaseStudies
     */
    int xMouse;// The integer xMouse contains the value of the x coord that the mouse is currently at
    int YMouse;// The integer variable yMouse contains the value of the y coord that the mouse is currently at
    public CaseStudies() {
        initComponents();// Initialises all the the base framework
        Timer t = new Timer(100, new CaseStudies.Listener());// Creating the timer for the real time clock on the top of the toolbar
        t.start();//Starts the timer as the frame is opened
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Icon = new javax.swing.JLabel();
        Settings = new javax.swing.JLabel();
        yourClock = new javax.swing.JLabel();
        HelpToolbar = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        ExitButtonToolbar = new javax.swing.JLabel();
        FrameDrag = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        MainPane = new javax.swing.JTabbedPane();
        Physical = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Back_Phy = new javax.swing.JButton();
        BoscastleButton = new javax.swing.JButton();
        BiharButton = new javax.swing.JButton();
        ThreeGorgesButton = new javax.swing.JButton();
        RiverColeButton = new javax.swing.JButton();
        TomboloButton = new javax.swing.JButton();
        SandDunesButton = new javax.swing.JButton();
        Human = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Back_Human = new javax.swing.JButton();
        FranceButton = new javax.swing.JButton();
        ImmigrationButton = new javax.swing.JButton();
        TransmigrationButton = new javax.swing.JButton();
        ChinaButton = new javax.swing.JButton();
        InnerCityButton = new javax.swing.JButton();
        RuralButton = new javax.swing.JButton();
        OpenNotes = new javax.swing.JButton();
        Default = new javax.swing.JLabel();
        ChesilBeach = new javax.swing.JLabel();
        SandDunes = new javax.swing.JLabel();
        ThreeGorgesDam = new javax.swing.JLabel();
        RiverCole = new javax.swing.JLabel();
        Bihar = new javax.swing.JLabel();
        Boscastle = new javax.swing.JLabel();
        ProFrance = new javax.swing.JLabel();
        AntiChina = new javax.swing.JLabel();
        Transmigration = new javax.swing.JLabel();
        Immigration = new javax.swing.JLabel();
        InnerCity = new javax.swing.JLabel();
        RuralArea = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Geovise - Case Studies");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1018, 636));
        setResizable(false);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/Geovise/IconAssets/VolcanicSmall.png"))); // NOI18N
        getContentPane().add(Icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        Settings.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/Geovise/IconAssets/options.png"))); // NOI18N
        Settings.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SettingsMouseClicked(evt);
            }
        });
        getContentPane().add(Settings, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 0, -1, -1));

        yourClock.setForeground(new java.awt.Color(255, 255, 255));
        yourClock.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(yourClock, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 28));

        HelpToolbar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/Geovise/IconAssets/help.png"))); // NOI18N
        HelpToolbar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HelpToolbarMouseClicked(evt);
            }
        });
        getContentPane().add(HelpToolbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 0, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/Geovise/IconAssets/minimize.png"))); // NOI18N
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 0, 30, 27));

        ExitButtonToolbar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/Geovise/IconAssets/quit.png"))); // NOI18N
        ExitButtonToolbar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ExitButtonToolbarFocusGained(evt);
            }
        });
        ExitButtonToolbar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitButtonToolbarMouseClicked(evt);
            }
        });
        getContentPane().add(ExitButtonToolbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 0, -1, -1));

        FrameDrag.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                FrameDragMouseDragged(evt);
            }
        });
        FrameDrag.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                FrameDragMousePressed(evt);
            }
        });
        getContentPane().add(FrameDrag, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 30));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/Geovise/Assets/Toolbar_Medium.png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 27));

        MainPane.setName(""); // NOI18N

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Physical Geography");

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel5.setText("Case Studies");

        Back_Phy.setText("Back");
        Back_Phy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Back_PhyActionPerformed(evt);
            }
        });

        BoscastleButton.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        BoscastleButton.setText("Boscastle 2004 (Flooding)");
        BoscastleButton.setPreferredSize(new java.awt.Dimension(129, 21));
        BoscastleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoscastleButtonActionPerformed(evt);
            }
        });

        BiharButton.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        BiharButton.setText("Bihar 2008 (Flooding)");
        BiharButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BiharButtonActionPerformed(evt);
            }
        });

        ThreeGorgesButton.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        ThreeGorgesButton.setText("Three Gorges Dam, China");
        ThreeGorgesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThreeGorgesButtonActionPerformed(evt);
            }
        });

        RiverColeButton.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        RiverColeButton.setText("Restoring The River Cole");
        RiverColeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RiverColeButtonActionPerformed(evt);
            }
        });

        TomboloButton.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        TomboloButton.setText("Tombolo: Chesil Beach ");
        TomboloButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TomboloButtonActionPerformed(evt);
            }
        });

        SandDunesButton.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        SandDunesButton.setText("Sand Dunes: Formby");
        SandDunesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SandDunesButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PhysicalLayout = new javax.swing.GroupLayout(Physical);
        Physical.setLayout(PhysicalLayout);
        PhysicalLayout.setHorizontalGroup(
            PhysicalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(PhysicalLayout.createSequentialGroup()
                .addGroup(PhysicalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PhysicalLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel5))
                    .addGroup(PhysicalLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(Back_Phy, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(PhysicalLayout.createSequentialGroup()
                .addGroup(PhysicalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(RiverColeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TomboloButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SandDunesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ThreeGorgesButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BoscastleButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BiharButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        PhysicalLayout.setVerticalGroup(
            PhysicalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PhysicalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(BoscastleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BiharButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ThreeGorgesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(RiverColeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(TomboloButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(SandDunesButton, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                .addGap(140, 140, 140)
                .addComponent(Back_Phy)
                .addContainerGap())
        );

        MainPane.addTab("Physical", Physical);

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel1.setText("Human Geography");

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Case Studies");

        Back_Human.setText("Back");
        Back_Human.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Back_HumanActionPerformed(evt);
            }
        });

        FranceButton.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        FranceButton.setText("Pro Natalist France");
        FranceButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        FranceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FranceButtonActionPerformed(evt);
            }
        });

        ImmigrationButton.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        ImmigrationButton.setText("Immigration Control");
        ImmigrationButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ImmigrationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ImmigrationButtonActionPerformed(evt);
            }
        });

        TransmigrationButton.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        TransmigrationButton.setText("Transmigration");
        TransmigrationButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        TransmigrationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TransmigrationButtonActionPerformed(evt);
            }
        });

        ChinaButton.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        ChinaButton.setText("Anti Natalist China");
        ChinaButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ChinaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChinaButtonActionPerformed(evt);
            }
        });

        InnerCityButton.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        InnerCityButton.setText("Inner City Area & Suburbs");
        InnerCityButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        InnerCityButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InnerCityButtonActionPerformed(evt);
            }
        });

        RuralButton.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        RuralButton.setText("Rural area ");
        RuralButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        RuralButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RuralButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout HumanLayout = new javax.swing.GroupLayout(Human);
        Human.setLayout(HumanLayout);
        HumanLayout.setHorizontalGroup(
            HumanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HumanLayout.createSequentialGroup()
                .addGroup(HumanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(HumanLayout.createSequentialGroup()
                        .addGroup(HumanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(HumanLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(HumanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(HumanLayout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addComponent(Back_Human, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HumanLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(RuralButton, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(InnerCityButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ImmigrationButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TransmigrationButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ChinaButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(FranceButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        HumanLayout.setVerticalGroup(
            HumanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HumanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(FranceButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ChinaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TransmigrationButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ImmigrationButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(InnerCityButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(RuralButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 152, Short.MAX_VALUE)
                .addComponent(Back_Human)
                .addContainerGap())
        );

        MainPane.addTab("Human", Human);

        getContentPane().add(MainPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 23, 170, 620));
        MainPane.getAccessibleContext().setAccessibleName("");

        OpenNotes.setText("Open Notes");
        OpenNotes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpenNotesActionPerformed(evt);
            }
        });
        getContentPane().add(OpenNotes, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 590, 110, 30));

        Default.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/Geovise/Assets/CaseStudy_Background_Main.jpg"))); // NOI18N
        getContentPane().add(Default, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 850, 620));

        ChesilBeach.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/Geovise/Assets/CaseStudy_ChesilBeach.png"))); // NOI18N
        getContentPane().add(ChesilBeach, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 850, 620));

        SandDunes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/Geovise/Assets/CaseStudy_SandDunes.png"))); // NOI18N
        getContentPane().add(SandDunes, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 850, 620));

        ThreeGorgesDam.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/Geovise/Assets/CaseStudy_ThreeGorgesDam.jpg"))); // NOI18N
        getContentPane().add(ThreeGorgesDam, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 850, 620));

        RiverCole.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/Geovise/Assets/CaseStudy_RiverCole.jpg"))); // NOI18N
        getContentPane().add(RiverCole, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 850, 620));

        Bihar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/Geovise/Assets/CaseStudy_Bihar.jpg"))); // NOI18N
        getContentPane().add(Bihar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 850, 620));

        Boscastle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/Geovise/Assets/CaseStudy_Boscastle.jpg"))); // NOI18N
        getContentPane().add(Boscastle, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 850, 620));

        ProFrance.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ProFrance.setForeground(new java.awt.Color(255, 204, 51));
        ProFrance.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ProFrance.setText("Pro France");
        getContentPane().add(ProFrance, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 850, 620));

        AntiChina.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        AntiChina.setForeground(new java.awt.Color(255, 204, 51));
        AntiChina.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AntiChina.setText("Anti China");
        getContentPane().add(AntiChina, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 850, 620));

        Transmigration.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Transmigration.setForeground(new java.awt.Color(255, 204, 51));
        Transmigration.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Transmigration.setText("Transmigration");
        getContentPane().add(Transmigration, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 850, 620));

        Immigration.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Immigration.setForeground(new java.awt.Color(255, 204, 51));
        Immigration.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Immigration.setText("Immigration");
        getContentPane().add(Immigration, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 850, 620));

        InnerCity.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        InnerCity.setForeground(new java.awt.Color(255, 204, 51));
        InnerCity.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        InnerCity.setText("Inner City");
        getContentPane().add(InnerCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 850, 620));

        RuralArea.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        RuralArea.setForeground(new java.awt.Color(255, 204, 51));
        RuralArea.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RuralArea.setText("Rural China");
        getContentPane().add(RuralArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 850, 620));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    class Listener implements ActionListener
    {
        public void actionPerformed(ActionEvent e)
        {
            Calendar rightNow = Calendar.getInstance();
            
            int hour = rightNow.get(Calendar.HOUR_OF_DAY);
            int min = rightNow.get(Calendar.MINUTE);
            int sec = rightNow.get(Calendar.SECOND);
            int AMPM = rightNow.get(Calendar.AM_PM);
            if(AMPM == 1) // AMPM is an integer variable, 1 being PM and 0 being AM. Its an integer so have to check if 1 or 0
            {
                if(min < 10) // The format does not add a zero to values below 10, so 10:09 would display 10:9 without this.
                {
                    yourClock.setText(hour + ":" + "0" + min + " " + "PM"); // The format does not add a zero to values below 10, so 10:09 would display 10:9 without this.
                }
                else // However if its not below 10 then the extra 0 is not required.
                {
                    yourClock.setText(hour + ":" + min + " " + "PM"); // No extra zero, just outputting the time with PM
                }

            }

            else // AMPM can either be 1 or 0, 1 is PM so the only other value is 0 which must be AM, no need for if statement
            {
                if(min < 10)// The format does not add a zero to values below 10, so 10:09 would display 10:9 without this.
                {
                    yourClock.setText(hour + ":" + "0" + min + " " + "AM"); // Uses same code from above to add extra zero.
                }
                else
                {
                 yourClock.setText(hour + ":" + min + " " + "AM");
                }


            }
        }
    }
    private void Back_HumanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Back_HumanActionPerformed
        this.dispose(); // Closes the currrent window which is open
        new MainUI().setVisible(true); // Opens up the main menu window
    }//GEN-LAST:event_Back_HumanActionPerformed

    private void Back_PhyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Back_PhyActionPerformed
        this.dispose(); // Closes the currrent window which is open
        new MainUI().setVisible(true); // Opens up the main menu window
    }//GEN-LAST:event_Back_PhyActionPerformed

    private void BoscastleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoscastleButtonActionPerformed
        resetCaseStudyVisible(); //Runs the resetCaseStudy function which sets all of the case study jLabels to invisible so the user cannot see them
        Boscastle.setVisible(true); // Then sets the Boscastle image to visible
    }//GEN-LAST:event_BoscastleButtonActionPerformed

    private void SettingsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SettingsMouseClicked
        if(OptionOpen != true) //Checks if the boolean variable is false, so is the options menu open
        {   
            new Options().setVisible(true); //If its not open then it will open up the options menu
            OptionOpen = true; // It will also change the value of the variable to true. Of course once they click on the settings again it wont go into the statement above.
        }
        else // However if the options menu is open, and the variable is true
        {
            if(OptionOpen == true)
            {
                JOptionPane.showMessageDialog(null, "WARNING : Settings Already Open !"); //It will display a dialog box, and not open up the options menu
            }
        }
    }//GEN-LAST:event_SettingsMouseClicked

    private void ExitButtonToolbarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ExitButtonToolbarFocusGained

    }//GEN-LAST:event_ExitButtonToolbarFocusGained

    private void ExitButtonToolbarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitButtonToolbarMouseClicked
        System.exit(0); // Exits the program
    }//GEN-LAST:event_ExitButtonToolbarMouseClicked

    private void FrameDragMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FrameDragMouseDragged
        int x = evt.getXOnScreen();//Grabbing the final location where it is dragged to, for x coord
        int y = evt.getYOnScreen();//Grabbing the final location where it is dragged to, for y coord

        this.setLocation(x - xMouse, y - YMouse);//Offsetting to fix issue where it jumps to the right when moved.
    }//GEN-LAST:event_FrameDragMouseDragged

    private void FrameDragMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FrameDragMousePressed
        xMouse = evt.getX();//Grabbing the current x coord of the mouse when clicked
        YMouse = evt.getY(); //Grabbing the current y coord of the mouse when clicked
    }//GEN-LAST:event_FrameDragMousePressed

    private void BiharButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BiharButtonActionPerformed
        resetCaseStudyVisible(); //Runs the resetCaseStudy function which sets all of the case study jLabels to invisible so the user cannot see them
        Bihar.setVisible(true); // Then sets the Bihar image to visible
    }//GEN-LAST:event_BiharButtonActionPerformed

    private void ThreeGorgesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThreeGorgesButtonActionPerformed
        resetCaseStudyVisible(); //Runs the resetCaseStudy function which sets all of the case study jLabels to invisible so the user cannot see them
        ThreeGorgesDam.setVisible(true); // Then sets the Three gorges dam image to visible
    }//GEN-LAST:event_ThreeGorgesButtonActionPerformed

    private void RiverColeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RiverColeButtonActionPerformed
        resetCaseStudyVisible(); //Runs the resetCaseStudy function which sets all of the case study jLabels to invisible so the user cannot see them
        RiverCole.setVisible(true); // Then sets the River Cole image to visible
    }//GEN-LAST:event_RiverColeButtonActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown

    }//GEN-LAST:event_formComponentShown

    private void OpenNotesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpenNotesActionPerformed
        new my.Geovise.Notes().setVisible(true); //Opens up the notes window
    }//GEN-LAST:event_OpenNotesActionPerformed

    private void FranceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FranceButtonActionPerformed
        resetCaseStudyVisible(); //Runs the resetCaseStudy function which sets all of the case study jLabels to invisible so the user cannot see them
        ProFrance.setVisible(true); // Then sets the Pro France image to visible
    }//GEN-LAST:event_FranceButtonActionPerformed

    private void ImmigrationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ImmigrationButtonActionPerformed
        resetCaseStudyVisible(); //Runs the resetCaseStudy function which sets all of the case study jLabels to invisible so the user cannot see them
        Immigration.setVisible(true); // Then sets the Immigration image to visible
    }//GEN-LAST:event_ImmigrationButtonActionPerformed

    private void TransmigrationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TransmigrationButtonActionPerformed
        resetCaseStudyVisible(); //Runs the resetCaseStudy function which sets all of the case study jLabels to invisible so the user cannot see them
        Transmigration.setVisible(true); // Then sets the Transmigration image to visible
    }//GEN-LAST:event_TransmigrationButtonActionPerformed

    private void ChinaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChinaButtonActionPerformed
        resetCaseStudyVisible(); //Runs the resetCaseStudy function which sets all of the case study jLabels to invisible so the user cannot see them
        AntiChina.setVisible(true); // Then sets the Anti Natalist China image to visible
    }//GEN-LAST:event_ChinaButtonActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        this.setIconImage(new ImageIcon(getClass().getResource("Volcanic.png")).getImage());//Sets the default icon of the window to a custom .png file (The volcano icon)
    }//GEN-LAST:event_formWindowOpened

    private void TomboloButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TomboloButtonActionPerformed
        resetCaseStudyVisible(); //Runs the resetCaseStudy function which sets all of the case study jLabels to invisible so the user cannot see them
        ChesilBeach.setVisible(true); // Then sets the Chesil Beach image to visible
    }//GEN-LAST:event_TomboloButtonActionPerformed

    private void SandDunesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SandDunesButtonActionPerformed
        resetCaseStudyVisible(); //Runs the resetCaseStudy function which sets all of the case study jLabels to invisible so the user cannot see them
        SandDunes.setVisible(true); // Then sets the Sand Dunes image to visible
    }//GEN-LAST:event_SandDunesButtonActionPerformed

    private void InnerCityButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InnerCityButtonActionPerformed
        resetCaseStudyVisible(); //Runs the resetCaseStudy function which sets all of the case study jLabels to invisible so the user cannot see them
        InnerCity.setVisible(true); // Then sets the Inner City image to visible
    }//GEN-LAST:event_InnerCityButtonActionPerformed

    private void RuralButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RuralButtonActionPerformed
        resetCaseStudyVisible(); //Runs the resetCaseStudy function which sets all of the case study jLabels to invisible so the user cannot see them
        RuralArea.setVisible(true); // Then sets the Rural Area image to visible
    }//GEN-LAST:event_RuralButtonActionPerformed

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        setExtendedState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabel6MouseClicked

    private void HelpToolbarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HelpToolbarMouseClicked
        this.dispose(); // Closes the current active window
        new Help.MainHelp().setVisible(true); // Opens the help menu
    }//GEN-LAST:event_HelpToolbarMouseClicked

    public void resetCaseStudyVisible()
    {
        Default.setVisible(false);
        Boscastle.setVisible(false);
        Bihar.setVisible(false);
        ThreeGorgesDam.setVisible(false);
        RiverCole.setVisible(false);   
        ChesilBeach.setVisible(false);
        SandDunes.setVisible(false); 
        RuralArea.setVisible(false); 
        ProFrance.setVisible(false);
        AntiChina.setVisible(false);
        Transmigration.setVisible(false);
        Immigration.setVisible(false);
        InnerCity.setVisible(false);        
    }      
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CaseStudies.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CaseStudies.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CaseStudies.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CaseStudies.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CaseStudies().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AntiChina;
    private javax.swing.JButton Back_Human;
    private javax.swing.JButton Back_Phy;
    private javax.swing.JLabel Bihar;
    private javax.swing.JButton BiharButton;
    private javax.swing.JLabel Boscastle;
    private javax.swing.JButton BoscastleButton;
    private javax.swing.JLabel ChesilBeach;
    private javax.swing.JButton ChinaButton;
    private javax.swing.JLabel Default;
    private javax.swing.JLabel ExitButtonToolbar;
    private javax.swing.JLabel FrameDrag;
    private javax.swing.JButton FranceButton;
    private javax.swing.JLabel HelpToolbar;
    private javax.swing.JPanel Human;
    private javax.swing.JLabel Icon;
    private javax.swing.JLabel Immigration;
    private javax.swing.JButton ImmigrationButton;
    private javax.swing.JLabel InnerCity;
    private javax.swing.JButton InnerCityButton;
    private javax.swing.JTabbedPane MainPane;
    private javax.swing.JButton OpenNotes;
    private javax.swing.JPanel Physical;
    private javax.swing.JLabel ProFrance;
    private javax.swing.JLabel RiverCole;
    private javax.swing.JButton RiverColeButton;
    private javax.swing.JLabel RuralArea;
    private javax.swing.JButton RuralButton;
    private javax.swing.JLabel SandDunes;
    private javax.swing.JButton SandDunesButton;
    private javax.swing.JLabel Settings;
    private javax.swing.JButton ThreeGorgesButton;
    private javax.swing.JLabel ThreeGorgesDam;
    private javax.swing.JButton TomboloButton;
    private javax.swing.JLabel Transmigration;
    private javax.swing.JButton TransmigrationButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel yourClock;
    // End of variables declaration//GEN-END:variables
}
