package my.Geovise; //Stating what package this file is part of. It is part of the my.contacteditor package

import javax.swing.JOptionPane; //Importing a specific part of the swing API, the JOptionPane
import java.sql.*; // Importing the SQL so that we can execute SQL statements on the database
import javax.swing.*; // Importing the swing API
import java.awt.event.*; // Importing the events so when the user click on a button then it executes the subsuqent code.
import java.awt.Toolkit; // Importing the toolkit too allow for the use of the awt ToolKit
import java.util.Calendar; // Importing the Calendar part of the util section
import java.util.Random; //Importing the random integer
import static my.Geovise.Login.USERNAME;

public class MainUI extends javax.swing.JFrame { // Extends the JFrame allows for the gui functionality

    /**
     * Creates new form MainUI
     */
    int xMouse; // The integer xMouse contains the value of the x coord that the mouse is currently at
    int YMouse; // The integer variable yMouse contains the value of the y coord that the mouse is currently at
    String Username = Login.USERNAME; // This string variable username contains the name of the user that is grabbed from the databse in the login section. Login.USERNAME is a global variable
    public static boolean NotesOpen = false;
    public static boolean OptionOpen = false;
    public MainUI() {
        initComponents(); // Initialises all the the base framework
        Timer t = new Timer(100, new MainUI.Listener()); // Creating the timer for the real time clock on the top of the toolbar
        t.start(); //Starts the timer as the frame is opened
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        UsernameText = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Icon = new javax.swing.JLabel();
        Settings = new javax.swing.JLabel();
        MinimiseToolbar = new javax.swing.JLabel();
        HelpToolbar = new javax.swing.JLabel();
        ExitButtonToolbar = new javax.swing.JLabel();
        yourClock = new javax.swing.JLabel();
        FrameDrag = new javax.swing.JLabel();
        QuickFact = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        WelcomeUserText = new javax.swing.JLabel();
        Quiz = new javax.swing.JButton();
        CaseStudies = new javax.swing.JButton();
        QuickFacts = new javax.swing.JButton();
        Notes = new javax.swing.JButton();
        Help = new javax.swing.JButton();
        Logout = new javax.swing.JLabel();
        ExitButton = new javax.swing.JLabel();
        SettingsButton = new javax.swing.JLabel();
        ButtonPane = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Geovise - Main Menu");
        setMinimumSize(new java.awt.Dimension(1018, 568));
        setUndecorated(true);
        setResizable(false);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
                formWindowLostFocus(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        UsernameText.setFont(new java.awt.Font("Trebuchet MS", 3, 18)); // NOI18N
        UsernameText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        UsernameText.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                UsernameTextComponentShown(evt);
            }
        });
        getContentPane().add(UsernameText, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 170, 30));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/Geovise/Assets/Geovise_Logo-Alt.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 40, 330, 120));

        Icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/Geovise/IconAssets/VolcanicSmall.png"))); // NOI18N
        getContentPane().add(Icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        Settings.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/Geovise/IconAssets/options.png"))); // NOI18N
        Settings.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SettingsMouseClicked(evt);
            }
        });
        getContentPane().add(Settings, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 0, -1, -1));

        MinimiseToolbar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/Geovise/IconAssets/minimize.png"))); // NOI18N
        MinimiseToolbar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MinimiseToolbarMouseClicked(evt);
            }
        });
        getContentPane().add(MinimiseToolbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 0, 30, 27));

        HelpToolbar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/Geovise/IconAssets/help.png"))); // NOI18N
        HelpToolbar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HelpToolbarMouseClicked(evt);
            }
        });
        getContentPane().add(HelpToolbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 0, -1, -1));

        ExitButtonToolbar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/Geovise/IconAssets/quit.png"))); // NOI18N
        ExitButtonToolbar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ExitButtonToolbarFocusGained(evt);
            }
        });
        ExitButtonToolbar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitButtonToolbarMouseClicked(evt);
            }
        });
        getContentPane().add(ExitButtonToolbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 0, -1, -1));

        yourClock.setForeground(new java.awt.Color(255, 255, 255));
        yourClock.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(yourClock, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 28));

        FrameDrag.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                FrameDragMouseDragged(evt);
            }
        });
        FrameDrag.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                FrameDragMousePressed(evt);
            }
        });
        getContentPane().add(FrameDrag, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 30));

        QuickFact.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        QuickFact.setForeground(new java.awt.Color(255, 204, 0));
        QuickFact.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        QuickFact.setAutoscrolls(true);
        getContentPane().add(QuickFact, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 490, 830, 70));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/Geovise/Assets/Toolbar_Medium.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 27));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/Geovise/Assets/Main_Menu_Background.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, -1, 570));

        WelcomeUserText.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        WelcomeUserText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        WelcomeUserText.setText("Welcome");
        WelcomeUserText.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                WelcomeUserTextComponentShown(evt);
            }
        });
        getContentPane().add(WelcomeUserText, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 170, 30));

        Quiz.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        Quiz.setText("Quiz");
        Quiz.setToolTipText("");
        Quiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuizActionPerformed(evt);
            }
        });
        getContentPane().add(Quiz, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 90, 30));

        CaseStudies.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        CaseStudies.setText("Case Studies");
        CaseStudies.setToolTipText("");
        CaseStudies.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CaseStudiesActionPerformed(evt);
            }
        });
        getContentPane().add(CaseStudies, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 90, 30));

        QuickFacts.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        QuickFacts.setText("Quick Facts");
        QuickFacts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuickFactsActionPerformed(evt);
            }
        });
        getContentPane().add(QuickFacts, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 90, 30));

        Notes.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        Notes.setText("Notes");
        Notes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NotesActionPerformed(evt);
            }
        });
        getContentPane().add(Notes, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 90, 30));

        Help.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        Help.setText("Help");
        Help.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HelpActionPerformed(evt);
            }
        });
        getContentPane().add(Help, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 90, 30));

        Logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/Geovise/IconAssets/logout.png"))); // NOI18N
        Logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogoutMouseClicked(evt);
            }
        });
        getContentPane().add(Logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 540, -1, -1));

        ExitButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/Geovise/IconAssets/exit.png"))); // NOI18N
        ExitButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitButtonMouseClicked(evt);
            }
        });
        getContentPane().add(ExitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 540, -1, -1));

        SettingsButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SettingsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/Geovise/IconAssets/options.png"))); // NOI18N
        SettingsButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SettingsButtonMouseClicked(evt);
            }
        });
        getContentPane().add(SettingsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 540, 160, -1));

        ButtonPane.setEditable(false);
        ButtonPane.setColumns(20);
        ButtonPane.setRows(5);
        ButtonPane.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(ButtonPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 568));

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jButton2.setText("Credits");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 490, 90, 30));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    class Listener implements ActionListener
    {
        public void actionPerformed(ActionEvent e)
        {
            
            Calendar rightNow = Calendar.getInstance(); //Creating a new calendar which will act as the base for the clock

            int hour = rightNow.get(Calendar.HOUR_OF_DAY); //Integer variable for the hour, it grabs the HOUR_OF_DAY from the calendar import
            int min = rightNow.get(Calendar.MINUTE);// Setting the current minuite to an integer variable called min.
            int AMPM = rightNow.get(Calendar.AM_PM);// Setting wheter the time is currently AM or PM, this is also an integer variable called AMPM
            if(AMPM == 1)// AMPM is an integer variable, 1 being PM and 0 being AM. Its an integer so have to check if 1 or 0
            {
                if(min < 10)// The format does not add a zero to values below 10, so 10:09 would display 10:9 without this.
                {
                    yourClock.setText(hour + ":" + "0" + min + " " + "PM");// The format does not add a zero to values below 10, so 10:09 would display 10:9 without this.
                }
                else// However if its not below 10 then the extra 0 is not required.
                {
                    yourClock.setText(hour + ":" + min + " " + "PM");// No extra zero, just outputting the time with PM
                }

            }

            else// AMPM can either be 1 or 0, 1 is PM so the only other value is 0 which must be AM, no need for if statement
            {
                if(min < 10)// The format does not add a zero to values below 10, so 10:09 would display 10:9 without this.
                {
                    yourClock.setText(hour + ":" + "0" + min + " " + "PM");// Uses same code from above to add extra zero.
                }
                else
                {
                 yourClock.setText(hour + ":" + min + " " + "PM");// No extra zero, just outputting the time with AM
                 }


            }

        }
    }
    private void QuizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuizActionPerformed
        this.dispose(); //Closes the current window which is open, so the main menu
        new Quiz().setVisible(true); // Opens up the quiz window
    }//GEN-LAST:event_QuizActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) { //When the form is opened the following is executed
        UsernameText.setText(String.valueOf(Login.USERNAME + "!")); // Sets the greeting message. Sets the content of the JLabel to the global variable Login.USERNAME
        this.setIconImage(new ImageIcon(getClass().getResource("Volcanic.png")).getImage()); //replaces the default java icon with a custom icon image.
    }

    private void WelcomeUserTextComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_WelcomeUserTextComponentShown

    }//GEN-LAST:event_WelcomeUserTextComponentShown

    private void CaseStudiesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CaseStudiesActionPerformed
        this.dispose(); // Closes the current window which is open, so the main menu
        new CaseStudies().setVisible(true); // Opens up the case studies menu
    }//GEN-LAST:event_CaseStudiesActionPerformed

    private void UsernameTextComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_UsernameTextComponentShown

    }//GEN-LAST:event_UsernameTextComponentShown

    private void SettingsMouseClicked(java.awt.event.MouseEvent evt) {  //Executed when the user clicks on the settings icon on the top right of the frame, in the toolbar                                    
        if(OptionOpen != true) //Checks if the boolean variable is false, so is the options menu open
        {   
            new Options().setVisible(true); //If its not open then it will open up the options menu
            OptionOpen = true; // It will also change the value of the variable to true. Of course once they click on the settings again it wont go into the statement above.
        }
        else // However if the options menu is open, and the variable is true
        {
            if(OptionOpen == true)
            {
                JOptionPane.showMessageDialog(null, "WARNING : Settings Already Open !"); //It will display a dialog box, and not open up the options menu
            }
        }
    }                                       

    private void ExitButtonToolbarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ExitButtonToolbarFocusGained

    }//GEN-LAST:event_ExitButtonToolbarFocusGained

    private void ExitButtonToolbarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitButtonToolbarMouseClicked
        System.exit(0); //Exits the progam
    }//GEN-LAST:event_ExitButtonToolbarMouseClicked

    private void LogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutMouseClicked
        this.dispose(); // Closes the current window which is in focus
        JOptionPane.showMessageDialog(null, "Logout successfull"); //Informs the user that they have been logged out in a dialog box
        new Login().setVisible(true); //Redirects them to the login window by setting its visiblity to true.
    }//GEN-LAST:event_LogoutMouseClicked

    private void ExitButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitButtonMouseClicked
        System.exit(0); //Exits the progam
    }//GEN-LAST:event_ExitButtonMouseClicked

    private void SettingsButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SettingsButtonMouseClicked
        if(OptionOpen != true) //Checks if the boolean variable is false, so is the options menu open
        {   
            new Options().setVisible(true); //If its not open then it will open up the options menu
            OptionOpen = true; // It will also change the value of the variable to true. Of course once they click on the settings again it wont go into the statement above.
        }
        else // However if the options menu is open, and the variable is true
        {
            if(OptionOpen == true)
            {
                JOptionPane.showMessageDialog(null, "WARNING : Settings Already Open !"); //It will display a dialog box, and not open up the options menu
            }
        }
    }//GEN-LAST:event_SettingsButtonMouseClicked

    private void FrameDragMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FrameDragMouseDragged
        int x = evt.getXOnScreen();//Grabbing the final location where it is dragged to, for x coord
        int y = evt.getYOnScreen();//Grabbing the final location where it is dragged to, for y coord

        this.setLocation(x - xMouse, y - YMouse);//Offsetting to fix issue where it jumps to the right when moved.
    }//GEN-LAST:event_FrameDragMouseDragged

    private void FrameDragMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FrameDragMousePressed
        xMouse = evt.getX();//Grabbing the current x coord of the mouse when clicked
        YMouse = evt.getY(); //Grabbing the current y coord of the mouse when clicked
    }//GEN-LAST:event_FrameDragMousePressed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

    }//GEN-LAST:event_jButton2ActionPerformed

    private void QuickFactsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuickFactsActionPerformed
        Random rn = new Random(); //Creating a new random integer
        int factNum = rn.nextInt(25) + 1; //Creating a new integer value between 1 and 10
        System.out.println("Fact No. " + factNum); //Debug line to output the value
        switch (factNum)
        {
            case 1: QuickFact.setText("Fact : 200 million years ago most of the earth's land was one huge continent named Pangaea");
                    break; // Fact 1
                    
            case 2: QuickFact.setText("Fact: Millions of years ago, the place that is now New York City was on the equator.");
                    break;   // Fact 2
                    
            case 3: QuickFact.setText("Fact: Millions of years ago Antarctica was a rain forest.");
                    break; // Fact 3
                    
            case 4: QuickFact.setText("Fact: The Atlantic Ocean grows wider by an inch a year while the Pacific Ocean shrinks.");
                    break;// Fact 4
                    
            case 5: QuickFact.setText("Fact: The coastline of the Atlantic Ocean sinks about four inches every 100 years.");
                    break;// Fact 5
                    
            case 6: QuickFact.setText("Fact: A new island, called Surtsey, was born in 1963.");
                    break; // Fact 6
                    
            case 7: QuickFact.setText("Fact: Millions of years ago India broke away from Africa and created the Himalaya Mountains.");
                    break;// Fact 7
                    
            case 8: QuickFact.setText("Fact: A new island, called Surtsey, was born in 1963. It is a volcanic island off the coast of Iceland.");
                    break;// Fact 8 
                    
            case 9:QuickFact.setText("Fact: Our world is moving constantly, spinning at a rate of 1,000 miles per hour. ");
                    break;// Fact 9
                    
            case 10:QuickFact.setText("Fact: We are whirling around the sun at 20 miles per second.");
                    break;// Fact 10
                
            case 11:QuickFact.setText("Fact: Cannes is farther north than Milwaukee.");
                    break;// Fact 11
                
            case 12:QuickFact.setText("Fact: Estcourt Station with a population of 4 is in the northernmost tip of Maine.");
                    break;// Fact 12
        
            case 13:QuickFact.setText("Fact: Glasgow is About 280 miles North of London.");
                    break;// Fact 13
                
            case 14:QuickFact.setText("Fact: England is Smaller Than Louisiana.");
                    break;// Fact 14
              
            case 15:QuickFact.setText("Fact: The tallest wave in history was the 1958 Ltuya Bay megatsunami, a height of 1720 feet!");
                    break;// Fact 15
                    
            case 16:QuickFact.setText("Fact: Forest growth in the US has exceeded harves since the 1940's.");
                    break;// Fact 16    
                    
            case 17:QuickFact.setText("Fact: Every person in the world can fit in Texas and be given over 1000 sq ft to live in.");
                    break;// Fact 17 
                    
            case 18:QuickFact.setText("Fact: Venice island was built on a foundation of tree trunks.");
                    break;// Fact 18
                    
            case 19:QuickFact.setText("Fact: The Sahara desert expands at about 1km per month.");
                    break;// Fact 19
                    
            case 20:QuickFact.setText("Fact: The North Atlantic gets 2.5cm wider each year !");
                    break;// Fact 20
                    
            case 21:QuickFact.setText("Fact: The water of the Antarctica is so cold that nothing can rot there.");
                    break;// Fact 21
                    
            case 22:QuickFact.setText("Fact: The percentage of Africa that is wilderness is 28%, the percentage is North America is 38%");
                    break;// Fact 22
                    
            case 23:QuickFact.setText("Fact: A volcano has enough power to shoot ash as high as 50km into the atmosphere.");
                    break;// Fact 23
                    
            case 24:QuickFact.setText("Fact: The Atlantic Ocean is saltier than the pacific Ocean!");
                    break;// Fact 24 
                    
            case 25:QuickFact.setText("Fact: Australia's Great Barrier Reef is 1250 miles long!");
                    break;// Fact 25                    
        }
    }//GEN-LAST:event_QuickFactsActionPerformed

    private void NotesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NotesActionPerformed
        if(NotesOpen != true) //Checks if the boolean variable is false, so is the Notes window open
        {   
            new Notes().setVisible(true); //If its not open then it will open up the Notes menu
            NotesOpen = true; // It will also change the value of the variable to true. Of course once they click on the settings again it wont go into the statement above.
        }
        else // However if the Notes menu is open, and the variable is true
        {
            if(NotesOpen == true)
            {
                JOptionPane.showMessageDialog(null, "WARNING : Notes Already Open !"); //It will display a dialog box, and not open up the Notes menu
            }
        }
    }//GEN-LAST:event_NotesActionPerformed

    private void formWindowLostFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowLostFocus

    }//GEN-LAST:event_formWindowLostFocus

    private void HelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HelpActionPerformed
        this.dispose(); // Closes the current active window
        new Help.MainHelp().setVisible(true); // Opens the help menu
    }//GEN-LAST:event_HelpActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed

    }//GEN-LAST:event_formWindowClosed

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus

    }//GEN-LAST:event_formWindowGainedFocus

    private void HelpToolbarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HelpToolbarMouseClicked
        this.dispose(); // Closes the current active window
        new Help.MainHelp().setVisible(true); // Opens the help menu
    }//GEN-LAST:event_HelpToolbarMouseClicked

    private void MinimiseToolbarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimiseToolbarMouseClicked
        setExtendedState(JFrame.ICONIFIED); //Minimises to the task bar if clicked
    }//GEN-LAST:event_MinimiseToolbarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainUI().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea ButtonPane;
    private javax.swing.JButton CaseStudies;
    private javax.swing.JLabel ExitButton;
    private javax.swing.JLabel ExitButtonToolbar;
    private javax.swing.JLabel FrameDrag;
    private javax.swing.JButton Help;
    private javax.swing.JLabel HelpToolbar;
    private javax.swing.JLabel Icon;
    private javax.swing.JLabel Logout;
    private javax.swing.JLabel MinimiseToolbar;
    private javax.swing.JButton Notes;
    private javax.swing.JLabel QuickFact;
    private javax.swing.JButton QuickFacts;
    private javax.swing.JButton Quiz;
    private javax.swing.JLabel Settings;
    private javax.swing.JLabel SettingsButton;
    public javax.swing.JLabel UsernameText;
    public javax.swing.JLabel WelcomeUserText;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel yourClock;
    // End of variables declaration//GEN-END:variables
}