package my.Geovise;//Stating what package this file is part of. It is part of the my.contacteditor package


import java.sql.Connection; // Importing the connection libaries for the SQL database, allowing me to conenct to it later on
import java.sql.DriverManager; // Allows for the use of drivers and managing them
import java.sql.PreparedStatement; // Allows me to execute and use prepared statements for SQL statements
import javax.swing.ImageIcon; // Allows me to set the icon of the frame
import javax.swing.JFrame;
import javax.swing.JOptionPane; // Allows for the use of option panes
import static my.Geovise.Login.USERNAME;// Importing the gloabl username variable to check what the username of the user is
import static my.Geovise.MainUI.OptionOpen; // Importing the gloabl variable Option open, from the main menu to check if the options are open or not

public class Options extends javax.swing.JFrame { // Extends the JFrame allows for the gui functionality

    /**
     * Creates new form Options
     */
    int xMouse;// The integer xMouse contains the value of the x coord that the mouse is currently at
    int YMouse;// The integer variable yMouse contains the value of the y coord that the mouse is currently at
    public static boolean quizFirstTime = true; // Creates a new global variable to check if its the users first time using the quiz, default set to false.
    public static boolean CloseMenu = false; // Creates a new global variable to check if the menu should be close, default to false
    public Options() {
        initComponents();// Initialises all the the base framework
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        HelpToolbar = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ExitButtonToolbar = new javax.swing.JLabel();
        Settings = new javax.swing.JLabel();
        FrameDrag = new javax.swing.JLabel();
        Icon = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ExitButton = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        ResetAccount = new javax.swing.JButton();
        DeleteAccount = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Geovise - Options");
        setAlwaysOnTop(true);
        setMinimumSize(new java.awt.Dimension(199, 456));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(197, 467));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        HelpToolbar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/Geovise/IconAssets/help.png"))); // NOI18N
        HelpToolbar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HelpToolbarMouseClicked(evt);
            }
        });
        getContentPane().add(HelpToolbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/Geovise/IconAssets/minimize.png"))); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 20, 27));

        ExitButtonToolbar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/Geovise/IconAssets/quit.png"))); // NOI18N
        ExitButtonToolbar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ExitButtonToolbarFocusGained(evt);
            }
        });
        ExitButtonToolbar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitButtonToolbarMouseClicked(evt);
            }
        });
        getContentPane().add(ExitButtonToolbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, -1, -1));

        Settings.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/Geovise/IconAssets/options.png"))); // NOI18N
        Settings.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SettingsMouseClicked(evt);
            }
        });
        getContentPane().add(Settings, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, -1, -1));

        FrameDrag.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                FrameDragMouseDragged(evt);
            }
        });
        FrameDrag.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                FrameDragMousePressed(evt);
            }
        });
        getContentPane().add(FrameDrag, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 30));

        Icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/Geovise/IconAssets/VolcanicSmall.png"))); // NOI18N
        getContentPane().add(Icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/Geovise/Assets/Toolbar_Short.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 27));

        ExitButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/Geovise/IconAssets/exit.png"))); // NOI18N
        ExitButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitButtonMouseClicked(evt);
            }
        });
        getContentPane().add(ExitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 440, -1, -1));

        jLabel1.setText("remove your account !");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 190, 20));

        jLabel6.setText("WARNING :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 100, 20));

        ResetAccount.setText("Reset Account Score");
        ResetAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetAccountActionPerformed(evt);
            }
        });
        getContentPane().add(ResetAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 150, -1));

        DeleteAccount.setText("Delete Account");
        DeleteAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteAccountActionPerformed(evt);
            }
        });
        getContentPane().add(DeleteAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 150, -1));

        jLabel7.setText("This will Permenantly");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 140, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        this.setIconImage(new ImageIcon(getClass().getResource("Volcanic.png")).getImage());//replaces the default java icon with a custom icon image.
    }//GEN-LAST:event_formWindowOpened

    private void SettingsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SettingsMouseClicked
        if(OptionOpen != true) //Checks if the boolean variable is false, so is the options menu open
        {   
            new Options().setVisible(true); //If its not open then it will open up the options menu
            OptionOpen = true; // It will also change the value of the variable to true. Of course once they click on the settings again it wont go into the statement above.
        }
        else // However if the options menu is open, and the variable is true
        {
            if(OptionOpen == true)
            {
                JOptionPane.showMessageDialog(null, "WARNING : Settings Already Open !"); //It will display a dialog box, and not open up the options menu
            }
        }
    }//GEN-LAST:event_SettingsMouseClicked

    private void ExitButtonToolbarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitButtonToolbarMouseClicked
        System.exit(0);// Exits the program
    }//GEN-LAST:event_ExitButtonToolbarMouseClicked

    private void ExitButtonToolbarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ExitButtonToolbarFocusGained

    }//GEN-LAST:event_ExitButtonToolbarFocusGained

    private void FrameDragMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FrameDragMousePressed
        xMouse = evt.getX();//Grabbing the current x coord of the mouse when clicked
        YMouse = evt.getY(); //Grabbing the current y coord of the mouse when clicked
    }//GEN-LAST:event_FrameDragMousePressed

    private void FrameDragMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FrameDragMouseDragged
        int x = evt.getXOnScreen();//Grabbing the final location where it is dragged to, for x coord
        int y = evt.getYOnScreen();//Grabbing the final location where it is dragged to, for y coord

        this.setLocation(x - xMouse, y - YMouse);//Offsetting to fix issue where it jumps to the right when moved.
    }//GEN-LAST:event_FrameDragMouseDragged

    private void ExitButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitButtonMouseClicked
        this.dispose(); // Closes the current active window
    }//GEN-LAST:event_ExitButtonMouseClicked

    private void ResetAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetAccountActionPerformed

        System.out.println("Restting Score..."); // Debugging line of code stating that it has run the function
        System.out.println(my.Geovise.Quiz.Score); // Outputs the users score
        System.out.println(USERNAME); // Outputs the current username of the user that is currently logged in.
        try // Attempts to....
        {
            Class.forName("com.mysql.jdbc.Driver").newInstance();  // MySQL database connection
            Connection conn = DriverManager.getConnection("jdbc:mysql://sql8.freemysqlhosting.net:3306/sql8133165?" + "user=sql8133165&password=" + "qWIM2CcWQf");
            // ^^ Creating the connection to the database with the username and password
            PreparedStatement pst = conn.prepareStatement("UPDATE Login SET HighestScore =0   WHERE username ='"+USERNAME+"'"); 
            // ^^ Resets the highest score of the user to 0 and then executes the statement.
            pst.executeUpdate();
        }
        catch(Exception e)
        {

        }
        JOptionPane.showMessageDialog(null, "Account Score Reset !"); // Informing the user that their account score has been reset
        this.dispose(); // Closes the current active frame
        CloseMenu = true; // Sets the boolean variable to true, indicating the window should be closed
        new my.Geovise.Login().setVisible(true); // Opens up the login window, essentialy logging out the user
    }//GEN-LAST:event_ResetAccountActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        my.Geovise.MainUI.OptionOpen = false; // Once the window is closed, it sets the variable to false to indicate that it is not open any more
    }//GEN-LAST:event_formWindowClosed

    private void DeleteAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteAccountActionPerformed
        System.out.println("Delete Account..."); // Debugging line of code, stating it has run the function
        try // Attempts to...
        {
            Class.forName("com.mysql.jdbc.Driver").newInstance();  // MySQL database connection
            Connection conn = DriverManager.getConnection("jdbc:mysql://sql8.freemysqlhosting.net:3306/sql8133165?" + "user=sql8133165&password=" + "qWIM2CcWQf");
            // ^^ Creating the connection to the database with the username and password
            PreparedStatement pst = conn.prepareStatement("DELETE FROM Login WHERE username ='"+USERNAME+"'");
            // ^^ Resets the highest score of the user to 0 and then executes the statement.
            pst.executeUpdate();
        }
        catch(Exception e)
        {

        }
        JOptionPane.showMessageDialog(null, "Account Deleted, Please Restart!");// Informing the user that their account has now been deleted
        System.exit(0);
    }//GEN-LAST:event_DeleteAccountActionPerformed

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        setExtendedState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabel4MouseClicked

    private void HelpToolbarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HelpToolbarMouseClicked
        this.dispose(); // Closes the current active window
        new Help.MainHelp().setVisible(true); // Opens the help menu
    }//GEN-LAST:event_HelpToolbarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Options.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Options.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Options.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Options.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Options().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DeleteAccount;
    private javax.swing.JLabel ExitButton;
    private javax.swing.JLabel ExitButtonToolbar;
    private javax.swing.JLabel FrameDrag;
    private javax.swing.JLabel HelpToolbar;
    private javax.swing.JLabel Icon;
    private javax.swing.JButton ResetAccount;
    private javax.swing.JLabel Settings;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
