package my.Geovise;//Stating what package this file is part of. It is part of the my.contacteditor package

import java.sql.Connection;//Importing the connection libaries for the SQL database, allowing me to conenct to it later on
import java.sql.DriverManager;// Allows for the use of drivers and managing them
import javax.swing.JOptionPane; //Allows for the use of option panes
import java.sql.*; // Importing all of the sql libraries for use in DB modification
import java.awt.event.*;// Importing the action event and listener etc., to check when the user clicks on an object in the frame
import java.util.Calendar; //  Allows me to create the clock etc.
import javax.swing.JFrame;
import javax.swing.Timer;
import static my.Geovise.MainUI.OptionOpen; // Global Variables

public class Register extends javax.swing.JFrame {// Extends the JFrame allows for the gui functionality

    /**
     * Creates new form Register
     */
    int XMouse;// The integer xMouse contains the value of the x coord that the mouse is currently at
    int YMouse;// The integer variable yMouse contains the value of the y coord that the mouse is currently at
    public Register() {
        initComponents();// Initialises all the the base framework
        Timer t = new Timer(100, new Register.Listener());// Creating the timer for the real time clock on the top of the toolbar
        t.start();//Starts the timer as the frame is opened
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Icon = new javax.swing.JLabel();
        ExitButtonToolbar1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Settings1 = new javax.swing.JLabel();
        HelpToolbar = new javax.swing.JLabel();
        yourClock = new javax.swing.JLabel();
        FrameDrag = new javax.swing.JLabel();
        ConfirmButton = new javax.swing.JLabel();
        ExitButton = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        UsernameField = new javax.swing.JTextField();
        PasswordField = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Geovise - Register");
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(848, 480));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/Geovise/IconAssets/VolcanicSmall.png"))); // NOI18N
        getContentPane().add(Icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        ExitButtonToolbar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/Geovise/IconAssets/quit.png"))); // NOI18N
        ExitButtonToolbar1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ExitButtonToolbar1FocusGained(evt);
            }
        });
        ExitButtonToolbar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitButtonToolbar1MouseClicked(evt);
            }
        });
        getContentPane().add(ExitButtonToolbar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 0, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/Geovise/IconAssets/minimize.png"))); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 0, 30, 27));

        Settings1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/Geovise/IconAssets/options.png"))); // NOI18N
        Settings1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Settings1MouseClicked(evt);
            }
        });
        getContentPane().add(Settings1, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 0, -1, -1));

        HelpToolbar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/Geovise/IconAssets/help.png"))); // NOI18N
        HelpToolbar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HelpToolbarMouseClicked(evt);
            }
        });
        getContentPane().add(HelpToolbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 0, -1, -1));

        yourClock.setForeground(new java.awt.Color(255, 255, 255));
        yourClock.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(yourClock, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 28));

        FrameDrag.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/Geovise/Assets/Toolbar_Large.png"))); // NOI18N
        FrameDrag.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                FrameDragMouseDragged(evt);
            }
        });
        FrameDrag.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                FrameDragMousePressed(evt);
            }
        });
        getContentPane().add(FrameDrag, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, -1));

        ConfirmButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/Geovise/IconAssets/confirm.png"))); // NOI18N
        ConfirmButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ConfirmButtonMouseClicked(evt);
            }
        });
        getContentPane().add(ConfirmButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 250, -1, -1));

        ExitButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/Geovise/IconAssets/exit.png"))); // NOI18N
        ExitButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitButtonMouseClicked(evt);
            }
        });
        getContentPane().add(ExitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 250, -1, -1));

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("To Register Please Enter Your Chosen Username And Password Below ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 850, 90));

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Username:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 170, 80, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Password:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 220, 80, -1));

        UsernameField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        UsernameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsernameFieldActionPerformed(evt);
            }
        });
        getContentPane().add(UsernameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 160, 120, 30));

        PasswordField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        PasswordField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                PasswordFieldKeyPressed(evt);
            }
        });
        getContentPane().add(PasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 210, 120, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/Geovise/Assets/LoginBackground.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jButton1.setForeground(new java.awt.Color(204, 0, 0));
        jButton1.setText("Create Account");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 120, 60));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
class Listener implements ActionListener //Creating the Listener class to update
    {
        public void actionPerformed(ActionEvent e)
        {
            Calendar rightNow = Calendar.getInstance(); //Gets the current time from the Calendar Libary
                // These variables below are aquired from the calendar library.
            int hour = rightNow.get(Calendar.HOUR_OF_DAY); // Setting the current hour to an integer variable called hour
            int min = rightNow.get(Calendar.MINUTE); // Setting the current minuite to an integer variable called min.
            int AMPM = rightNow.get(Calendar.AM_PM); // Setting wheter the time is currently AM or PM, this is also an integer variable called AMPM
            if(AMPM == 1) // AMPM is an integer variable, 1 being PM and 0 being AM. Its an integer so have to check if 1 or 0
            {
                if(min < 10) // The format does not add a zero to values below 10, so 10:09 would display 10:9 without this.
                {
                    yourClock.setText(hour + ":" + "0" + min + " " + "PM"); // The format does not add a zero to values below 10, so 10:09 would display 10:9 without this.
                }
                else // However if its not below 10 then the extra 0 is not required.
                {
                    yourClock.setText(hour + ":" + min + " " + "PM"); // No extra zero, just outputting the time with PM
                }

            }

            else // AMPM can either be 1 or 0, 1 is PM so the only other value is 0 which must be AM, no need for if statement
            {
                if(min < 10)// The format does not add a zero to values below 10, so 10:09 would display 10:9 without this.
                {
                    yourClock.setText(hour + ":" + "0" + min + " " + "AM"); // Uses same code from above to add extra zero.
                }
                else
                {
                 yourClock.setText(hour + ":" + min + " " + "AM");
                }


            }
        }
    }
    private void UsernameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsernameFieldActionPerformed

    }//GEN-LAST:event_UsernameFieldActionPerformed

    private void PasswordFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PasswordFieldKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER) // If the user has clicked on the password field and has then pressed enter/return on the keyboard
        {
            jButton1.doClick(); //Execute the button action to validate the login
        }
    }//GEN-LAST:event_PasswordFieldKeyPressed

    private void FrameDragMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FrameDragMouseDragged
        int x = evt.getXOnScreen();//Grabbing the final location where it is dragged to, for x coord
        int y = evt.getYOnScreen();//Grabbing the final location where it is dragged to, for y coord

        this.setLocation(x - XMouse, y - YMouse);//Offsetting to fix issue where it jumps to the right when moved.
    }//GEN-LAST:event_FrameDragMouseDragged

    private void FrameDragMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FrameDragMousePressed
        XMouse = evt.getX();//Grabbing the current x coord of the mouse when clicked
        YMouse = evt.getY(); //Grabbing the current y coord of the mouse when clicked
    }//GEN-LAST:event_FrameDragMousePressed

    private void ConfirmButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ConfirmButtonMouseClicked
        if(UsernameField.getText().length()==0)  // Checking for empty field
        JOptionPane.showMessageDialog(null, "Empty fields detected ! Please fill up all fields");
        else if(PasswordField.getPassword().length==0)  // Checking for empty field
        JOptionPane.showMessageDialog(null, "Empty fields detected ! Please fill up all fields");
        else{
            String user = UsernameField.getText();   // Collecting the input
            char[] pass = PasswordField.getPassword(); // Collecting the input
            String pwd = String.copyValueOf(pass);  // converting from array to string
            if(validate_login(user,pwd)){
                JOptionPane.showMessageDialog(null, "Your Account Has Now Been Created");
                this.dispose();
                new Login().setVisible(true);
            }
            else
            JOptionPane.showMessageDialog(null, "Error");
        }
    }//GEN-LAST:event_ConfirmButtonMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(UsernameField.getText().length()==0)  // Checking for empty field
        JOptionPane.showMessageDialog(null, "Empty fields detected ! Please fill up all fields");
        else if(PasswordField.getPassword().length==0)  // Checking for empty field
        JOptionPane.showMessageDialog(null, "Empty fields detected ! Please fill up all fields");
        else{
            String user = UsernameField.getText();   // Collecting the input
            char[] pass = PasswordField.getPassword(); // Collecting the input
            String pwd = String.copyValueOf(pass);  // converting from array to string
            if(validate_login(user,pwd)){
                JOptionPane.showMessageDialog(null, "Your Account Has Now Been Created");
                this.dispose();
                new Login().setVisible(true);
            }
            else
            JOptionPane.showMessageDialog(null, "Error");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ExitButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitButtonMouseClicked
        this.dispose(); //Closes the currently active window/frame
        new Login().setVisible(true); //Opens up the login window
    }//GEN-LAST:event_ExitButtonMouseClicked

    private void ExitButtonToolbar1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ExitButtonToolbar1FocusGained

    }//GEN-LAST:event_ExitButtonToolbar1FocusGained

    private void ExitButtonToolbar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitButtonToolbar1MouseClicked
        System.exit(0); // Exiting the program
    }//GEN-LAST:event_ExitButtonToolbar1MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        setExtendedState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabel5MouseClicked

    private void Settings1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Settings1MouseClicked
        if(OptionOpen != true) //Checks if the boolean variable is false, so is the options menu open
        {
            new Options().setVisible(true); //If its not open then it will open up the options menu
            OptionOpen = true; // It will also change the value of the variable to true. Of course once they click on the settings again it wont go into the statement above.
        }
        else // However if the options menu is open, and the variable is true
        {
            if(OptionOpen == true)
            {
                JOptionPane.showMessageDialog(null, "WARNING : Settings Already Open !"); //It will display a dialog box, and not open up the options menu
            }
        }
    }//GEN-LAST:event_Settings1MouseClicked

    private void HelpToolbarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HelpToolbarMouseClicked
        this.dispose(); // Closes the current active window
        new Help.MainHelp().setVisible(true); // Opens the help menu
    }//GEN-LAST:event_HelpToolbarMouseClicked

    private boolean validate_login(String user,String pwd) {
       System.out.println("Running Register Function...."); // Debugging line
       try{//Try and catch incase any errors are produced, such as a failed connection
       Class.forName("com.mysql.jdbc.Driver").newInstance();  // MySQL database connection
       Connection conn = DriverManager.getConnection("jdbc:mysql://sql8.freemysqlhosting.net:3306/sql8133165?" + "user=sql8133165&password=" + "qWIM2CcWQf");//Creating the connection w/ user and pass
       System.out.println("Connection passed");
       
       Statement sta = conn.createStatement();
       
       sta.executeUpdate("INSERT INTO Login(username, password) VALUES ('" + user +"','" + pwd +"' )");//Actual SQL statement
       System.out.println("Executing Statement...");
       sta.close();
       conn.close();                       
       return true;
   }
   catch(Exception e){
       e.printStackTrace();
       return false;
   }      
}
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ConfirmButton;
    private javax.swing.JLabel ExitButton;
    private javax.swing.JLabel ExitButtonToolbar1;
    private javax.swing.JLabel FrameDrag;
    private javax.swing.JLabel HelpToolbar;
    private javax.swing.JLabel Icon;
    private javax.swing.JPasswordField PasswordField;
    private javax.swing.JLabel Settings1;
    private javax.swing.JTextField UsernameField;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel yourClock;
    // End of variables declaration//GEN-END:variables
}
